version: "3.7"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: postgres
      POSTGRES_DB: filesdb
    volumes:
      - filesdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fileservice:
    build: .
    environment:
      PORT: 5000 
      DBHOST: db
      DBPASSWORD: pwd
      DBUSER: postgres
      DB: filesdb 
      DBPORT: 5432
    volumes:
      - filesstorage:/app/files
      - ./src:/app/src
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  filesstorage:
  filesdb:
